// AUTO-GENERADO desde la tienda web BAYONA.
// Fuente: SBAYONA-WEB-PRIME/src/config/shopProducts.js
// No inventar productos aquí. Ejecuta: node tools/sync-shop-catalog.mjs
export const SHOP_BASE_URL = "https://bayona-jet.vercel.app/shop";

export const SHOP_PRODUCTS = Object.freeze([
  {
    "id": "tank-top-performance",
    "name": "Tank Top Performance",
    "category": "Ropa Entreno",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$99.000 COP",
    "eurDisplay": "≈ €23",
    "usdDisplay": "≈ $25 USD",
    "description": "Entrenas libre. Nada frena tu movimiento.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=tank-top-performance"
  },
  {
    "id": "short-tecnico-bayona",
    "name": "Short Técnico BAYONA",
    "category": "Ropa Entreno",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$119.000 COP",
    "eurDisplay": "≈ €28",
    "usdDisplay": "≈ $30 USD",
    "description": "Te mueves sin límites. Comodidad en cada repetición.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=short-tecnico-bayona"
  },
  {
    "id": "legging-pro-mujer",
    "name": "Legging Pro Mujer",
    "category": "Ropa Entreno",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$149.000 COP",
    "eurDisplay": "≈ €35",
    "usdDisplay": "≈ $37 USD",
    "description": "Entrenas en serio. Soporte que sigue tu ritmo.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=legging-pro-mujer"
  },
  {
    "id": "camiseta-manga-larga",
    "name": "Camiseta Manga Larga",
    "category": "Ropa Entreno",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$139.000 COP",
    "eurDisplay": "≈ €32",
    "usdDisplay": "≈ $35 USD",
    "description": "Sigues adelante. Protección cuando el día exige más.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=camiseta-manga-larga"
  },
  {
    "id": "top-deportivo-mujer",
    "name": "Top Deportivo Mujer",
    "category": "Ropa Entreno",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$99.000 COP",
    "eurDisplay": "≈ €23",
    "usdDisplay": "≈ $25 USD",
    "description": "Te mueves segura. Soporte y libertad en cada sesión.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=top-deportivo-mujer"
  },
  {
    "id": "camiseta-compresion",
    "name": "Camiseta Compresión",
    "category": "Ropa Entreno",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$129.000 COP",
    "eurDisplay": "≈ €30",
    "usdDisplay": "≈ $32 USD",
    "description": "Tu ritmo no afloja. Ajuste que acompaña cada repetición.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=camiseta-compresion"
  },
  {
    "id": "hoodie-origins",
    "name": "Hoodie Origins",
    "category": "Ropa Lifestyle",
    "collection": "Origins",
    "collectionId": "origins",
    "priceDisplay": "$189.000 COP",
    "eurDisplay": "≈ €44",
    "usdDisplay": "≈ $47 USD",
    "description": "Tu primera pieza. El inicio del camino.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=hoodie-origins"
  },
  {
    "id": "hoodie-premium",
    "name": "Hoodie Premium",
    "category": "Ropa Lifestyle",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$249.000 COP",
    "eurDisplay": "≈ €58",
    "usdDisplay": "≈ $62 USD",
    "description": "Para los que van en serio. Presencia que se siente.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=hoodie-premium"
  },
  {
    "id": "camiseta-origins",
    "name": "Camiseta Origins",
    "category": "Ropa Lifestyle",
    "collection": "Origins",
    "collectionId": "origins",
    "priceDisplay": "$129.000 COP",
    "eurDisplay": "≈ €30",
    "usdDisplay": "≈ $32 USD",
    "description": "Tu identidad, sin ruido. Simple. Potente. Tuya.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=camiseta-origins"
  },
  {
    "id": "pantalon-jogger-premium",
    "name": "Pantalón Jogger Premium",
    "category": "Ropa Lifestyle",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$179.000 COP",
    "eurDisplay": "≈ €42",
    "usdDisplay": "≈ $45 USD",
    "description": "Representas dentro y fuera. Del gimnasio a la calle.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=pantalon-jogger-premium"
  },
  {
    "id": "gorra-bayona",
    "name": "Gorra BAYONA",
    "category": "Ropa Lifestyle",
    "collection": "Origins",
    "collectionId": "origins",
    "priceDisplay": "$89.000 COP",
    "eurDisplay": "≈ €21",
    "usdDisplay": "≈ $22 USD",
    "description": "Perteneces al camino. Lleva la marca donde vayas.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=gorra-bayona"
  },
  {
    "id": "chaqueta-windstopper",
    "name": "Chaqueta Windstopper",
    "category": "Ropa Lifestyle",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$289.000 COP",
    "eurDisplay": "≈ €67",
    "usdDisplay": "≈ $72 USD",
    "description": "No negocias con el clima. Sigues avanzando.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=chaqueta-windstopper"
  },
  {
    "id": "sudadero-recovery",
    "name": "Sudadero Recovery",
    "category": "Ropa Lifestyle",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$159.000 COP",
    "eurDisplay": "≈ €37",
    "usdDisplay": "≈ $40 USD",
    "description": "Bajas el ritmo sin perder identidad. Recupera con estilo.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=sudadero-recovery"
  },
  {
    "id": "calcetines-compresion-pack-3",
    "name": "Calcetines Compresión (pack 3)",
    "category": "Ropa Lifestyle",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$59.000 COP",
    "eurDisplay": "≈ €14",
    "usdDisplay": "≈ $15 USD",
    "description": "Cuidas cada detalle. Tu movimiento también empieza abajo.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=calcetines-compresion-pack-3"
  },
  {
    "id": "zapatillas-move",
    "name": "Zapatillas MOVE",
    "category": "Calzado",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$289.000 COP",
    "eurDisplay": "≈ €67",
    "usdDisplay": "≈ $72 USD",
    "description": "Te adaptas a cualquier terreno. Agarre y libertad total.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=zapatillas-move"
  },
  {
    "id": "zapatillas-trainer-pro",
    "name": "Zapatillas Trainer Pro",
    "category": "Calzado",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$349.000 COP",
    "eurDisplay": "≈ €81",
    "usdDisplay": "≈ $87 USD",
    "description": "Entrenas todo. Respuesta firme en cada movimiento.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=zapatillas-trainer-pro"
  },
  {
    "id": "zapatillas-parkour-free",
    "name": "Zapatillas Parkour Free",
    "category": "Calzado",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$399.000 COP",
    "eurDisplay": "≈ €93",
    "usdDisplay": "≈ $100 USD",
    "description": "Ves rutas donde otros ven muros. Agarre extremo.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=zapatillas-parkour-free"
  },
  {
    "id": "chanclas-recovery",
    "name": "Chanclas Recovery",
    "category": "Calzado",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$89.000 COP",
    "eurDisplay": "≈ €21",
    "usdDisplay": "≈ $22 USD",
    "description": "También avanzas cuando recuperas. Descanso para tus pies.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=chanclas-recovery"
  },
  {
    "id": "bandas-resistencia-set-5",
    "name": "Bandas de Resistencia (set 5)",
    "category": "Equipamiento",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$89.000 COP",
    "eurDisplay": "≈ €21",
    "usdDisplay": "≈ $22 USD",
    "description": "Tu gimnasio va contigo. Entrena donde quieras.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=bandas-resistencia-set-5"
  },
  {
    "id": "mancuernas-ajustables",
    "name": "Mancuernas Ajustables",
    "category": "Equipamiento",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$425.000 COP",
    "eurDisplay": "≈ €99",
    "usdDisplay": "≈ $106 USD",
    "description": "Construyes fuerza a tu manera. Infinitas posibilidades.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=mancuernas-ajustables"
  },
  {
    "id": "kit-reboot",
    "name": "Kit Reboot",
    "category": "Equipamiento",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$259.000 COP",
    "eurDisplay": "≈ €60",
    "usdDisplay": "≈ $65 USD",
    "description": "Decides volver más fuerte. Todo lo esencial para empezar.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=kit-reboot"
  },
  {
    "id": "foam-roller-pro",
    "name": "Foam Roller Pro",
    "category": "Equipamiento",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$79.000 COP",
    "eurDisplay": "≈ €18",
    "usdDisplay": "≈ $20 USD",
    "description": "Recuperas para volver mejor. Diez minutos que cuentan.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=foam-roller-pro"
  },
  {
    "id": "pelota-suiza",
    "name": "Pelota Suiza",
    "category": "Equipamiento",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$99.000 COP",
    "eurDisplay": "≈ €23",
    "usdDisplay": "≈ $25 USD",
    "description": "Controlas tu centro. Estabilidad que se siente.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=pelota-suiza"
  },
  {
    "id": "kettlebell-pro",
    "name": "Kettlebell Pro (8–24 kg)",
    "category": "Equipamiento",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$159.000–$299.000 COP",
    "eurDisplay": "≈ €37–€70",
    "usdDisplay": "≈ $40–$75 USD",
    "description": "Construyes poder real. Fuerza funcional en cada movimiento.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=kettlebell-pro"
  },
  {
    "id": "barra-dominadas-portatil",
    "name": "Barra Dominadas Portátil",
    "category": "Equipamiento",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$189.000 COP",
    "eurDisplay": "≈ €44",
    "usdDisplay": "≈ $47 USD",
    "description": "Tu casa también es territorio de fuerza. Eleva tu nivel.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=barra-dominadas-portatil"
  },
  {
    "id": "esterilla-premium",
    "name": "Esterilla Premium",
    "category": "Equipamiento",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$99.000 COP",
    "eurDisplay": "≈ €23",
    "usdDisplay": "≈ $25 USD",
    "description": "Creas tu espacio. Tu suelo, tu práctica, tu momento.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=esterilla-premium"
  },
  {
    "id": "guantes-parkour",
    "name": "Guantes de Parkour",
    "category": "Equipamiento",
    "collection": "Movement",
    "collectionId": "movement",
    "priceDisplay": "$89.000 COP",
    "eurDisplay": "≈ €21",
    "usdDisplay": "≈ $22 USD",
    "description": "Proteges tus manos. Domina cualquier muro.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=guantes-parkour"
  },
  {
    "id": "mochila-bayona",
    "name": "Mochila BAYONA",
    "category": "Equipamiento",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$189.000 COP",
    "eurDisplay": "≈ €44",
    "usdDisplay": "≈ $47 USD",
    "description": "Tu transformación viaja contigo. Lleva lo que te impulsa.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=mochila-bayona"
  },
  {
    "id": "botella-smart-bayona",
    "name": "Botella Smart BAYONA",
    "category": "Máquinas",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$79.000 COP",
    "eurDisplay": "≈ €18",
    "usdDisplay": "≈ $20 USD",
    "description": "Cuidas tu energía. Hidratación inteligente durante el día.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=botella-smart-bayona"
  },
  {
    "id": "pistola-masaje-pro",
    "name": "Pistola de Masaje Pro",
    "category": "Máquinas",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$299.000 COP",
    "eurDisplay": "≈ €70",
    "usdDisplay": "≈ $75 USD",
    "description": "Recuperas como entrenas: en serio. Potencia en tus manos.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=pistola-masaje-pro"
  },
  {
    "id": "reloj-inteligente-bayona",
    "name": "Reloj Inteligente BAYONA",
    "category": "Máquinas",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$599.000 COP",
    "eurDisplay": "≈ €139",
    "usdDisplay": "≈ $150 USD",
    "description": "Lees tu evolución. Tus métricas convierten esfuerzo en progreso.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=reloj-inteligente-bayona"
  },
  {
    "id": "banda-resistencia-inteligente",
    "name": "Banda de Resistencia Inteligente",
    "category": "Máquinas",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$359.000 COP",
    "eurDisplay": "≈ €83",
    "usdDisplay": "≈ $90 USD",
    "description": "Haces visible tu fuerza. Mide cada avance en vivo.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=banda-resistencia-inteligente"
  },
  {
    "id": "bascula-inteligente",
    "name": "Báscula Inteligente",
    "category": "Máquinas",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$249.000 COP",
    "eurDisplay": "≈ €58",
    "usdDisplay": "≈ $62 USD",
    "description": "Conoces tu punto de partida. Datos claros para avanzar mejor.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=bascula-inteligente"
  },
  {
    "id": "whey-protein-bayona",
    "name": "Whey Protein BAYONA",
    "category": "Suplementos",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$189.000 COP",
    "eurDisplay": "≈ €44",
    "usdDisplay": "≈ $47 USD",
    "description": "Alimentas tu progreso. Proteína limpia, recuperación real.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=whey-protein-bayona"
  },
  {
    "id": "creatina-monohidrato",
    "name": "Creatina Monohidrato",
    "category": "Suplementos",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$99.000 COP",
    "eurDisplay": "≈ €23",
    "usdDisplay": "≈ $25 USD",
    "description": "Construyes más fuerza. Potencia respaldada por ciencia.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=creatina-monohidrato"
  },
  {
    "id": "pre-workout-elite",
    "name": "Pre-Workout Elite",
    "category": "Suplementos",
    "collection": "Strength",
    "collectionId": "strength",
    "priceDisplay": "$149.000 COP",
    "eurDisplay": "≈ €35",
    "usdDisplay": "≈ $37 USD",
    "description": "Entras enfocado. Energía que acompaña tu intensidad.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=pre-workout-elite"
  },
  {
    "id": "omega-3-premium",
    "name": "Omega 3 Premium",
    "category": "Suplementos",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$89.000 COP",
    "eurDisplay": "≈ €21",
    "usdDisplay": "≈ $22 USD",
    "description": "Cuidas tu base. Recuperación que empieza desde dentro.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=omega-3-premium"
  },
  {
    "id": "multivitaminico-elite",
    "name": "Multivitamínico Elite",
    "category": "Suplementos",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$99.000 COP",
    "eurDisplay": "≈ €23",
    "usdDisplay": "≈ $25 USD",
    "description": "Sostienes tu ritmo. Una base diaria optimizada.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=multivitaminico-elite"
  },
  {
    "id": "colageno-hidrolizado",
    "name": "Colágeno Hidrolizado",
    "category": "Suplementos",
    "collection": "Recovery",
    "collectionId": "recovery",
    "priceDisplay": "$129.000 COP",
    "eurDisplay": "≈ €30",
    "usdDisplay": "≈ $32 USD",
    "description": "Te cuidas para seguir. Soporte diario desde dentro.",
    "shopUrl": "https://bayona-jet.vercel.app/shop?product=colageno-hidrolizado"
  }
].map((item) => Object.freeze(item)));

const BY_ID = new Map(SHOP_PRODUCTS.map((item) => [item.id, item]));
export function shopProduct(id) { return BY_ID.get(id) || null; }
export function shopProductUrl(id) {
  return BY_ID.get(id)?.shopUrl
    || (id ? SHOP_BASE_URL + "?product=" + encodeURIComponent(id) : SHOP_BASE_URL);
}
