-- =====================================================================
-- BAYONA — 0008_production_hardening.sql
-- Billing autoritativo, backups cloud, observabilidad y rollout.
-- =====================================================================

-- ---------------- BILLING ----------------
create table if not exists billing_subscriptions (
  user_id               uuid primary key references auth.users(id) on delete cascade,
  provider              text not null default 'stripe' check (provider='stripe'),
  customer_id           text unique,
  subscription_id       text unique,
  plan                   text not null check (plan in ('raiz','performance','elite')),
  status                 text not null check (status in (
                           'trialing','active','past_due','canceled','unpaid',
                           'incomplete','incomplete_expired','paused'
                         )),
  current_period_end     timestamptz,
  cancel_at_period_end   boolean not null default false,
  updated_at             timestamptz not null default now()
);

create table if not exists billing_webhook_events (
  event_id       text primary key,
  type           text not null,
  processed_at   timestamptz not null default now()
);

alter table billing_subscriptions enable row level security;
alter table billing_webhook_events enable row level security;

drop policy if exists "user reads own billing subscription" on billing_subscriptions;
create policy "user reads own billing subscription" on billing_subscriptions
for select to authenticated using (auth.uid()=user_id);

-- Sin INSERT/UPDATE/DELETE de billing para authenticated.
-- Solo service_role desde webhook puede cambiar entitlements.

-- ---------------- BACKUPS ----------------
create table if not exists user_backups (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  schema_version int not null check (schema_version > 0),
  checksum       text not null check (checksum ~ '^[a-f0-9]{64}$'),
  payload        jsonb not null,
  bytes          int not null check (bytes between 2 and 1000000),
  created_at     timestamptz not null default now(),
  check (octet_length(payload::text) <= 1000000)
);

create index if not exists user_backups_user_created_idx
  on user_backups(user_id, created_at desc);

alter table user_backups enable row level security;

create or replace function user_has_active_paid_plan(p_user uuid, p_plans text[])
returns boolean
language sql
stable
security definer
set search_path=public
as $
  select exists (
    select 1 from billing_subscriptions b
    where b.user_id=p_user
      and b.status in ('active','trialing')
      and b.plan=any(p_plans)
  );
$;

revoke all on function user_has_active_paid_plan(uuid,text[]) from public;
grant execute on function user_has_active_paid_plan(uuid,text[]) to authenticated;

drop policy if exists "user reads own backups" on user_backups;
create policy "user reads own backups" on user_backups
for select to authenticated using (auth.uid()=user_id);

drop policy if exists "user inserts own backups" on user_backups;
create policy "user inserts own backups" on user_backups
for insert to authenticated with check (
  auth.uid()=user_id
  and user_has_active_paid_plan(auth.uid(),array['performance','elite']::text[])
);

drop policy if exists "user deletes own backups" on user_backups;
create policy "user deletes own backups" on user_backups
for delete to authenticated using (auth.uid()=user_id);

create or replace function prune_user_backups()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  delete from user_backups
  where id in (
    select id from user_backups
    where user_id=new.user_id
    order by created_at desc
    offset 5
  );
  return new;
end;
$$;

drop trigger if exists user_backups_prune on user_backups;
create trigger user_backups_prune
after insert on user_backups
for each row execute function prune_user_backups();

-- ---------------- OBSERVABILIDAD ----------------
create table if not exists telemetry_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users(id) on delete set null,
  kind        text not null check (kind in (
                'client_error','unhandled_rejection','optional_load_error',
                'sync_error','api_error','web_vital','release'
              )),
  severity    text not null default 'info' check (severity in ('info','warn','error')),
  route       text,
  release     text,
  details     jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  check (octet_length(details::text) <= 4096)
);

create index if not exists telemetry_events_created_idx
  on telemetry_events(created_at desc);
create index if not exists telemetry_events_kind_idx
  on telemetry_events(kind, created_at desc);

alter table telemetry_events enable row level security;
-- Sin policies: el navegador no lee/escribe telemetría directamente.
-- Solo api/telemetry.js con service_role.

-- ---------------- ROLLOUT ----------------
create table if not exists feature_rollouts (
  key          text primary key,
  enabled      boolean not null default false,
  percentage   int not null default 0 check (percentage between 0 and 100),
  plans        text[] not null default '{}',
  payload      jsonb not null default '{}'::jsonb,
  updated_at   timestamptz not null default now()
);

alter table feature_rollouts enable row level security;

drop policy if exists "authenticated reads rollout flags" on feature_rollouts;
create policy "authenticated reads rollout flags" on feature_rollouts
for select to authenticated using (true);

insert into feature_rollouts(key,enabled,percentage,plans,payload)
values
  ('billing_checkout',false,0,array['raiz','performance','elite']::text[],'{}'::jsonb),
  ('cloud_backup',false,0,array['performance','elite']::text[],'{}'::jsonb),
  ('cloud_coach',false,0,array['raiz','performance','elite']::text[],'{}'::jsonb)
on conflict (key) do nothing;
